# Generated by Django 4.2.3 on 2023-07-14 12:12

import AuthorApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('bio', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to=AuthorApp.models.user_img_directory)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
